deepspeed --include localhost:5,6 --master_port=9903 src/train_bash.py \
    --deepspeed config/ds_config.json \
    --stage sft \
    --model_name_or_path /data2/models/llama2-13b-hf \
    --do_train \
    --dataset big_five_v2 \
    --template llama2 \
    --finetuning_type lora \
    --lora_target q_proj,v_proj \
    --output_dir output/llama2_13b_newT_ds \
    --overwrite_cache \
    --per_device_train_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate 5e-5 \
    --num_train_epochs 3.0 \
    --plot_loss \
    --bf16